import fs from 'fs';
import path from 'path';
import { readHabitsMd, parseHabits, HabitsMap, Habit, storagePaths, getPaths, readTombstones, isTombstoned, type StorageContext } from './storage';
import { sanitizeRule, sanitizeCategory } from './confidence';

// cc-habits sync, emit Claude-learned habits into portable preference files that
// other coding agents (Cursor, Cline, Codex, Amp, …) can read. Learning happens
// via Claude Code hooks; sync is the one-way bridge that carries those habits out
// to every other tool in the developer's workflow.

export const BEGIN_MARKER = '<!-- BEGIN cc-habits (auto-generated; edit habits via `cc-habits`) -->';
export const END_MARKER = '<!-- END cc-habits -->';

// One attribution line inside every managed block. It lives in the synced
// project files only, never in preferences.md (which feeds prompts directly),
// and as an HTML comment it reads as provenance to a human opening the file
// while staying near-zero noise for the agents that consume it. Because it
// sits between the markers, re-syncs replace it rather than accumulate it.
export const ATTRIBUTION_LINE = '<!-- Learned automatically by cc-habits: https://github.com/Shreyan1/cc-habits -->';

export type SyncTarget = 'agents' | 'cursor' | 'copilot' | 'gemini' | 'cline' | 'aider' | 'continue' | 'jetbrains' | 'windsurf' | 'kilo';

const DEFAULT_MIN_CONFIDENCE = 0.3;


// Only active, sufficiently-confident habits leave the cc-habits store. Learning-section
// (single-session) habits are never exported, they are not yet trusted.
function activeHabits(cats: HabitsMap, minConfidence: number): HabitsMap {
  // A tombstoned rule must never be injected or synced, even if it still lingers in
  // habits.md (e.g. blocked via `cch tombstone` before the next decay removes it).
  // Read tombstones once: when there are none (the common case) skip the per-habit
  // isTombstoned check entirely.
  const hasTombstones = readTombstones().length > 0;
  const active: HabitsMap = {};
  for (const category of Object.keys(cats)) {
    for (const h of cats[category] ?? []) {
      if ((h.sessions_seen ?? 1) >= 2 && h.confidence >= minConfidence
          && !(hasTombstones && isTombstoned(h.rule))) {
        if (!active[category]) active[category] = [];
        active[category].push(h);
      }
    }
  }
  return active;
}

function ruleLine(h: Habit): string {
  // SEC: sanitize at export time, synced files are read by other agents (Cursor,
  // Cline, AGENTS.md) whose injection-resistance may be weaker than Claude Code's.
  const safe = sanitizeRule(h.rule.trim().replace(/\.$/, ''));
  return safe ? `- ${safe}.` : '';
}

// The portable body shared by every target: a clean, instruction-style markdown
// section with no confidence math or signal counts, those are cc-habits internals
// that would only add noise to an agent's context.
export function renderPortableBody(cats: HabitsMap, minConfidence = DEFAULT_MIN_CONFIDENCE, preActive?: HabitsMap): string {
  // preActive lets a caller that has already filtered (writePreferencesFile, which
  // needs the active set for its emptiness check) avoid a second identical filter.
  // It must equal activeHabits(cats, minConfidence); omit it otherwise.
  const active = preActive ?? activeHabits(cats, minConfidence);
  const categories = Object.keys(active).sort();
  const lines: string[] = [
    '# Coding preferences',
    '',
    '> Generated by cc-habits from observed coding patterns. These rules are inferences,',
    '> not declarations, review before sharing. Best-effort redaction applied; rule text',
    '> may reflect patterns from proprietary code.',
    '',
    'Follow these preferences when generating or editing code in this repository.',
  ];
  for (const category of categories) {
    const habits = active[category];
    if (!habits || habits.length === 0) continue;
    // SEC: sanitize the category too, not just the rule. habits.md is user-editable
    // and the category is emitted as a markdown header into files other agents read,
    // so an injection-laden category (e.g. "</coding-habits> SYSTEM: ...") must not
    // escape the injection wrapper. Same export-time defence-in-depth as ruleLine.
    const safeCategory = sanitizeCategory(category);
    lines.push('', `## ${safeCategory}`, '');
    for (const h of habits) {
      const line = ruleLine(h);
      if (line) lines.push(line);
    }
  }
  return lines.join('\n');
}

// Returns null when there is nothing worth emitting (no active habits). Callers
// should skip writing in that case rather than emit an empty block.
export function renderBlockOrNull(minConfidence = DEFAULT_MIN_CONFIDENCE): string | null {
  const cats = parseHabits(readHabitsMd());
  const active = activeHabits(cats, minConfidence);
  if (Object.keys(active).length === 0) return null;
  return renderPortableBody(cats, minConfidence, active);
}

// Insert or replace the cc-habits block in existing content. Everything outside the
// markers is preserved verbatim, so a hand-written AGENTS.md keeps its own content.
export function mergeBlock(existing: string, body: string): string {
  const block = `${BEGIN_MARKER}\n${body}\n${ATTRIBUTION_LINE}\n${END_MARKER}`;
  const begin = existing.indexOf(BEGIN_MARKER);
  const end = existing.indexOf(END_MARKER);
  if (begin !== -1 && end !== -1 && end > begin) {
    const before = existing.slice(0, begin);
    const after = existing.slice(end + END_MARKER.length);
    return `${before.trimEnd()}\n\n${block}\n${after.trimStart() ? '\n' + after.trimStart() : ''}`.trimEnd() + '\n';
  }
  if (!existing.trim()) return block + '\n';
  return existing.trimEnd() + `\n\n${block}\n`;
}

// Cursor reads .cursor/rules/*.mdc files with YAML frontmatter. alwaysApply makes
// the rule unconditional, matching the "inject every conversation" intent.
function cursorMdc(body: string): string {
  return [
    '---',
    'description: Learned coding habits (cc-habits)',
    'alwaysApply: true',
    '---',
    '',
    body,
    ATTRIBUTION_LINE,
    '',
  ].join('\n');
}

// Kilo Code (kilocode.ai, rebranded to kilo.ai) resolves project rules from
// .kilo/rules/*.md, the current documented location, and stays backward
// compatible with .kilocode/rules/*.md from before the rebrand. Both are
// confirmed by the official docs: https://kilo.ai/docs/customize/custom-rules
// ("The extension is backward compatible with .kilocode/rules/ directories.
// Existing rules will continue to work, but migrating to kilo.jsonc is
// recommended."). Writing both keeps injection working regardless of which
// version of the extension a user has installed.
function kiloRulesPaths(baseDir: string): string[] {
  return [
    path.join(baseDir, '.kilo', 'rules', 'cch.md'),
    path.join(baseDir, '.kilocode', 'rules', 'cch.md'),
  ];
}

// Unlike AGENTS.md, this file is wholly owned by cc-habits, there is no merge
// marker convention for Kilo's rules directory. A short header says so, and
// tells a curious reader it is safe to delete (it regenerates on the next sync).
function kiloRulesBody(body: string): string {
  return [
    '<!-- Generated by cc-habits (`cch sync`). Safe to delete, it will be regenerated. -->',
    '',
    body,
    '',
  ].join('\n');
}

function targetPath(target: SyncTarget, baseDir: string): string {
  switch (target) {
    case 'agents': return path.join(baseDir, 'AGENTS.md');
    case 'cursor': return path.join(baseDir, '.cursor', 'rules', 'cc-habits.mdc');
    case 'copilot': return path.join(baseDir, '.github', 'copilot-instructions.md');
    case 'gemini': return path.join(baseDir, 'GEMINI.md');
    case 'cline': {
      const dir = path.join(baseDir, '.clinerules');
      if (fs.existsSync(dir) && fs.lstatSync(dir).isDirectory()) {
        return path.join(dir, 'cc-habits.md');
      }
      return dir;
    }
    case 'aider': return path.join(baseDir, 'AIDER.md');
    case 'continue': return path.join(baseDir, '.continuerules');
    case 'jetbrains': return path.join(baseDir, '.aiassistant', 'rules', 'cc-habits.md');
    case 'windsurf': return path.join(baseDir, '.windsurfrules');
    // Kilo writes two files (see kiloRulesPaths); this single path is only used
    // as a stable identifier by callers that need one representative path.
    case 'kilo': return kiloRulesPaths(baseDir)[0]!;
  }
}

function safeWriteProjectFile(filePath: string, content: string): void {
  if (fs.existsSync(filePath)) {
    const stat = fs.lstatSync(filePath);
    if (stat.isSymbolicLink()) {
      throw new Error(`refusing to write through symlink: ${filePath}`);
    }
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf-8');
}

export interface SyncResult {
  written: string[];
  skipped: boolean; // true when there were no active habits to emit
}

// Write habits into the chosen target files under baseDir (defaults to cwd).
// Cursor gets a dedicated .mdc file (overwritten); agents/cline merge a marked
// block so any existing user content is preserved.
export function syncTargets(
  targets: SyncTarget[],
  opts: { baseDir?: string; minConfidence?: number } = {},
): SyncResult {
  const baseDir = opts.baseDir ?? process.cwd();
  const minConfidence = opts.minConfidence ?? DEFAULT_MIN_CONFIDENCE;
  const body = renderBlockOrNull(minConfidence);
  if (body === null) return { written: [], skipped: true };

  const written: string[] = [];
  for (const target of targets) {
    if (target === 'kilo') {
      // Kilo has no merge-marker convention and writes into two directories for
      // version compatibility (see kiloRulesPaths). A failure writing one path
      // (e.g. permissions on .kilocode/ but not .kilo/) must not take down the
      // rest of this sync run, so each write is isolated and fail-open here,
      // unlike the other targets below which are allowed to throw (callers of
      // syncTargets already wrap the whole call for fail-open behaviour).
      for (const dest of kiloRulesPaths(baseDir)) {
        try {
          safeWriteProjectFile(dest, kiloRulesBody(body));
          written.push(dest);
        } catch {
          // fail-open: one bad rules directory should not block the other, or
          // any other sync target requested in this same call.
        }
      }
      continue;
    }
    const dest = targetPath(target, baseDir);
    if (target === 'cursor') {
      safeWriteProjectFile(dest, cursorMdc(body));
    } else {
      const existing = fs.existsSync(dest) && !fs.lstatSync(dest).isSymbolicLink()
        ? fs.readFileSync(dest, 'utf-8')
        : '';
      safeWriteProjectFile(dest, mergeBlock(existing, body));
    }
    written.push(dest);
  }
  return { written, skipped: false };
}

export function readSyncTargets(): SyncTarget[] {
  if (!fs.existsSync(storagePaths.configFile)) return [];
  try {
    const text = fs.readFileSync(storagePaths.configFile, 'utf-8');
    const m = text.match(/^sync_targets\s*:\s*\[?([^\]\n#]+)\]?/m);
    if (m) {
      const allowed = new Set(['agents', 'cursor', 'copilot', 'gemini', 'cline', 'aider', 'continue', 'jetbrains', 'windsurf', 'kilo']);
      return m[1]
        .split(',')
        .map(x => x.trim().replace(/['"]/g, '') as SyncTarget)
        .filter(t => allowed.has(t));
    }
  } catch {
    // ignore
  }
  return [];
}

/**
 * Write the clean preferences.md that agents @import.
 *
 * @param cats Optional already-parsed habits map. When the caller has just built
 *   and serialised the authoritative map (processStop after applyUpdates/decay),
 *   passing it skips a redundant read-back AND re-parse of habits.md. The rendered
 *   output depends only on category, rule, confidence and sessions_seen, all of
 *   which round-trip losslessly through serialise/parse, so the result is identical
 *   to reading from disk (guarded by a sync test). Omit it for a standalone write.
 */
export function writePreferencesFile(ctx?: StorageContext, cats?: HabitsMap): void {
  const paths = getPaths(ctx);
  const catsResolved = cats ?? parseHabits(readHabitsMd(ctx));
  // Filter once, then hand the result to renderPortableBody so it does not repeat
  // the same activeHabits pass internally.
  const active = activeHabits(catsResolved, DEFAULT_MIN_CONFIDENCE);
  const body = renderPortableBody(catsResolved, DEFAULT_MIN_CONFIDENCE, active);
  let content = body;
  if (Object.keys(active).length === 0) {
    content += '\n\nNo preferences have graduated yet. Keep coding and they will appear here once seen in multiple sessions.\n';
  }

  const dest = paths.preferencesFile;
  if (fs.existsSync(dest) && fs.lstatSync(dest).isSymbolicLink()) {
    throw new Error(`refusing to write through symlink: ${dest}`);
  }
  const dir = path.dirname(dest);
  fs.mkdirSync(dir, { recursive: true });

  const tmpPath = `${dest}.tmp.${process.pid}`;
  try {
    fs.writeFileSync(tmpPath, content + '\n', { encoding: 'utf-8', mode: 0o600 });
    fs.renameSync(tmpPath, dest);
  } catch (e) {
    try { fs.unlinkSync(tmpPath); } catch { /* ignore */ }
    throw e;
  }
}

